import fs from 'fs';
import os from 'os';
import path from 'path';
import { McpConfigService, McpConfig } from '../config/McpConfigService.js';
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);


export class DocScaffolder {
  constructor(protected mcpConfigService: McpConfigService) {}

    private writeIfNotExists(filePath: string, content: string) {
        if (!fs.existsSync(filePath)) {
          fs.writeFileSync(filePath, content);
        }
    }

    /**
     * Atomically copies a directory tree from src to dest.
     * Respects writeIfNotExists semantics: skips files that already exist in dest,
     * preserving any user customisations on re-runs.
     */
    private copyDirRecursive(src: string, dest: string): void {
        const entries = fs.readdirSync(src, { withFileTypes: true });
        for (const entry of entries) {
          const srcPath = path.join(src, entry.name);
          const destPath = path.join(dest, entry.name);
          if (entry.isDirectory()) {
            if (!fs.existsSync(destPath)) {
              fs.mkdirSync(destPath, { recursive: true });
            }
            this.copyDirRecursive(srcPath, destPath);
          } else if (!fs.existsSync(destPath)) {
            // Never overwrite — respect user customisations on re-run
            fs.copyFileSync(srcPath, destPath);
          }
        }
    }

    public scaffoldMcpConfigReference(projectRoot: string) {
        const docsDir = path.join(projectRoot, 'docs');
        if (!fs.existsSync(docsDir)) {
          fs.mkdirSync(docsDir, { recursive: true });
        }

        const sourceDoc = path.join(__dirname, '../../docs/technical/MCP_CONFIG_REFERENCE.md');
        const targetDoc = path.join(projectRoot, 'docs/MCP_CONFIG_REFERENCE.md');
        if (fs.existsSync(sourceDoc)) {
              fs.copyFileSync(sourceDoc, targetDoc);
            } else {
              // Fallback: create a basic reference doc if source doesn't exist
              const basicRef = `# MCP Config Reference

See the full documentation at: https://github.com/ForgeTest-AI/AppForge/blob/main/docs/MCP_CONFIG_REFERENCE.md

For the complete field reference, platform-specific settings, and examples, refer to the AppForge repository documentation.
`;
              fs.writeFileSync(targetDoc, basicRef, 'utf-8');
            }
    }

    public scaffoldPromptCheatbook(projectRoot: string) {
        const docsDir = path.join(projectRoot, 'docs');
        if (!fs.existsSync(docsDir)) {
          fs.mkdirSync(docsDir, { recursive: true });
        }

        const sourceDoc = path.join(__dirname, '../../docs/user/APPFORGE_PROMPT_CHEATBOOK.md');
        const targetDoc = path.join(projectRoot, 'docs/APPFORGE_PROMPT_CHEATBOOK.md');
        if (fs.existsSync(sourceDoc)) {
              fs.copyFileSync(sourceDoc, targetDoc);
            } else {
              // Fallback: create a basic cheatbook if source doesn't exist
              const basicCheatbook = `# AppForge Prompt Cheatbook

See the full cheatbook at: https://github.com/ForgeTest-AI/AppForge/blob/main/docs/APPFORGE_PROMPT_CHEATBOOK.md

For the complete prompt guide and best practices for working with AppForge MCP tools, refer to the AppForge repository documentation.
`;
              fs.writeFileSync(targetDoc, basicCheatbook, 'utf-8');
            }
    }

    public scaffoldMcpDocs(projectRoot: string) {
        const docsDir = path.join(projectRoot, 'docs');
        if (!fs.existsSync(docsDir)) {
          fs.mkdirSync(docsDir, { recursive: true });
        }

        const quickStart = `# AppForge Quick Start Guide

## Welcome to Your New Mobile Test Project!

This project was generated by **AppForge** - an AI-powered mobile test automation framework.

---

## ✅ Verify Setup

Run this command to confirm everything works:

\`\`\`bash
npm install
npm run test:smoke
\`\`\`

Expected output: **1 scenario (1 passed)** ✅

This dummy test confirms your Cucumber + WDIO + Appium stack is correctly configured.

---

## 🚀 Next Steps

### 1. Connect to a Device

\`\`\`bash
# Start Appium server
npx appium

# In another terminal, verify device connection
adb devices  # For Android
xcrun simctl list  # For iOS simulators
\`\`\`

### 2. Update App Path

Edit \`mcp-config.json\` and set the path to your mobile app:

\`\`\`json
{
  "mobile": {
    "capabilitiesProfiles": {
      "myDevice": {
        "appium:app": "/path/to/your/app.apk"
      }
    }
  }
}
\`\`\`

### 3. Write Your First Test

Replace the dummy code in:
- \`src/features/sample.feature\` - Write Gherkin scenarios
- \`src/step-definitions/sample.steps.ts\` - Implement step definitions  
- \`src/pages/LoginPage.ts\` - Add real selectors

---

## 📖 Useful Commands

| Command | Description |
|---------|-------------|
| \`npm run test:smoke\` | Run smoke tests |
| \`npm run test:regression\` | Run regression suite |
| \`npm test\` | Run all tests |

---

## 🛠️ Common Issues

### Appium Not Running
\`\`\`bash
npx appium
\`\`\`

### Device Not Found
- **Android**: Enable USB debugging, run \`adb devices\`
- **iOS**: Ensure simulator is booted

### Tests Timeout
Increase timeout in \`wdio.conf.ts\`:
\`\`\`typescript
cucumberOpts: {
  timeout: 120000  // 2 minutes
}
\`\`\`

---

## 📚 Learn More

- **MCP Config Reference**: \`mcp-config.json\` field documentation
- **AppForge GitHub**: Full documentation and examples
- **WebdriverIO Docs**: https://webdriver.io
- **Appium Docs**: https://appium.io

---

**Generated by AppForge v2.0.0**
`;
        this.writeIfNotExists(path.join(docsDir, 'APPFORGE_QUICK_START.md'), quickStart);
    }
}