// import type { Options } from '@wdio/types';
import type { Config } from 'webdriverio';


/**
 * WebdriverIO + Appium Configuration
 * Generated by Appium MCP Server.
 * Adjust capabilities for your target device/emulator.
 */
export const config: Config = {
  runner: 'local',
  hostname: 'localhost',
  port: 4723,
  path: '/',

  specs: ['./src/features/**/*.feature'],

  maxInstances: 1,

  capabilities: [{
    platformName: 'Android',
    'appium:automationName': 'UiAutomator2',
    'appium:deviceName': 'emulator-5554',
    // 'appium:app': '/path/to/your/app.apk',
    'appium:newCommandTimeout': 240,
    'appium:noReset': false,
  }],

  framework: 'cucumber',
  cucumberOpts: {
    require: ['./src/step-definitions/**/*.ts'],
    backtrace: false,
    dryRun: false,
    failFast: false,
    snippets: true,
    source: true,
    strict: false,
    timeout: 60000,
  },

  reporters: ['spec'],

  services: [['appium', {
    args: ['--relaxed-security'],
  }]],

  logLevel: 'info',
  waitforTimeout: 10000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,
};
